
name: deepfeps
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.24
  - scipy>=1.10
  - pandas>=2.0
  - tqdm>=4.66
  - scikit-learn>=1.2
  - networkx>=2.8
  - pip
  - pip:
      - biopython>=1.80
      - gensim>=4.3
      - transformers>=4.40
      - tokenizers>=0.15
      - torch>=2.1
      - karateclub>=1.3.3
      # - node2vec>=0.4.6
